#ifndef INSTRUCTION_H
#define INSTRUCTION_H 1

/* GUI instruction information */
struct instruction_gui_info {
    char const * const opname;
    char const * const desc;
    void *trampoline;
};

/* generated by script */
extern struct instruction_gui_info instruction_table[];

#endif /* INSTRUCTION_H */
